server:
  port: 8888

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kamothi/config-repo
          username: ${GIT_ID}
          password: ${GIT_PASS}